# **PyTorch Fundamentals**

See the [`PyTorch documentations`](https://docs.pytorch.org/docs/stable/index.html) for complete tutorial 

In [1]:
# Import PyTorch
import torch

In [2]:
# Check processor
!nvidia-smi

Sun Mar  8 19:18:32 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## **1. Introduction to Tensor**

PyTorch tensor are created using [`torch.Tensor()`](https://docs.pytorch.org/docs/stable/tensors.html)

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Get the dimension
scalar.ndim

0

In [5]:
# Get PyTorch tensor as int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# Get the dimension and shape
vector.ndim, vector.shape

(1, torch.Size([2]))

In [8]:
# Matrix
MATRIX = torch.tensor([
    [1, 2],
    [3, 4]
])

MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
# Get the dimension and shape
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [10]:
# Tensor
TENSOR = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
# Get the dimension and shape
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [12]:
# Get all of the first dimension
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
# Get all off the first and second dimension
TENSOR[0, 0]

tensor([1, 2, 3])

In [14]:
# Get the index 2 of the third dimension
TENSOR[0, 0, 2]

tensor(3)

### 1.1 Random tensor

Why random tensors?

> Random tensor are important because the way of neural networks learn is they start with tensors full of random numbers and then adjust those random number into better representation data

`Start with random numbers -> look at the data -> update those numbers -> look at the data -> update those numbers`

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0603, 0.6784, 0.1862, 0.9385],
        [0.5000, 0.7340, 0.9087, 0.6286],
        [0.0441, 0.5914, 0.3304, 0.7757]])

In [16]:
# Create a random tensor that similar to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # [heigh, width, color channels] -> [h, w, c]
random_image_size_tensor.size, random_image_size_tensor.shape, random_image_size_tensor.ndim

(<function Tensor.size>, torch.Size([224, 224, 3]), 3)

### 1.2 Zeros and ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 1.3 Creating a range of tensors and tensors-like

In [20]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 1.4 Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into when it comes to PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors wrong device

In [23]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3., 6., 9.],
    dtype=None, # What datatype is the tensor (e.g. float32)
    device=None, # What device you run your tensor on
    requires_grad=False # Whether or not to track gradient with this tensors operation
)

float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [27]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## **2. Getting Information from Tensors (Tensor Attribute)**

1. Datatype -> to get dtype from a tensor can use `tensor.dtype`
2. Shape -> to get shape from a tensor can use `tensor.shape`
3. Device -> to get device from a tensor can use `tensor.device`

In [28]:
# Create some tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0998, 0.3404, 0.2707, 0.5508],
        [0.6564, 0.4378, 0.5532, 0.9699],
        [0.8533, 0.1557, 0.4560, 0.1365]])

In [29]:
# Find out detail about some tensor
print(f"Tensor:\n{some_tensor}")

print("\nAttribute:")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Tensor:
tensor([[0.0998, 0.3404, 0.2707, 0.5508],
        [0.6564, 0.4378, 0.5532, 0.9699],
        [0.8533, 0.1557, 0.4560, 0.1365]])

Attribute:
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## **3. Manipulating Tensors (Tensor Operation)**

Tensor operations include:
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

### 3.1 Basic operations

In [30]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [31]:
# Addition
tensor + 10
torch.add(tensor, 10) # PyTorch built-in function

tensor([11, 12, 13])

In [32]:
# Substraction
tensor - 10
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [33]:
# Multiplication
tensor * 10
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [34]:
# Division
tensor / 10
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

### 3.2 Matrix multiplication

Two ways of performing multiplication in neural network and deep learning:
1. Element-wise operation (broadcastin)
2. Matrix Multiplication (dot product)

Rules of matrix multiplication:
- `(m, n) @ (n, m) = (m, m)`

In [35]:
# Element-wise multiplication
print(f"{tensor} * {tensor}")
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor) # 1*1 + 2*2 + 3*3 = 14

tensor(14)

In [37]:
# Matrix multiplication using @
tensor @ tensor

tensor(14)

In [38]:
%%time

value = 0
for i in range(len(tensor)): # len(tensor) -> len(first dimension of tensor)
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 784 µs, sys: 0 ns, total: 784 µs
Wall time: 1.79 ms


In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 41 µs, sys: 9 µs, total: 50 µs
Wall time: 93.9 µs


tensor(14)

## **4. One of the Most Common Errors in Deep Learning (Shape Errors)**

In [40]:
# Shape of matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is as the same as torch.matmul (it's an alias), but the input must be 2D

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor shape issues we can fix it by transposing it using `torch.transpose()` or `tensor.T`

A transpose switch the axes of a given tensor

In [41]:
print(f"tensor_A:\n{tensor_A}\n")
print(f"tensor_B.T:\n{tensor_B.T}")

tensor_A:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

tensor_B.T:
tensor([[ 7,  9, 11],
        [ 8, 10, 12]])


In [42]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### 4.1 Finding the min, max, mean, sum, etc (tensor aggregation)

In [43]:
# Create a x
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [45]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [46]:
# Find the mean - note: the torch.mean() requires float32 dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### 4.2 Finding the positional min and max

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# Finding the index of the minimum value
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [50]:
# Finding the index of the maximum value
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### 4.3 Change tensor datatype

In [51]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [52]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [53]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### 4.4 Reshaping, stacking, squeezing, unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension from a tensor
* Permute - return a view of the input with dimensions permuted (swaped) in a certain way

In [54]:
# Create a tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [55]:
# Add an extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [56]:
# Change the view
y = x.view(1, 10)
y, y.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [57]:
# Changing y changes x (because a view of tensor share the same memory as the original input)
y[0, 0] = 5.
y, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [58]:
# Stack tensors on top of each other
x_stacked = torch.stack((x, x, x), dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [59]:
x_stacked = torch.stack((x, x, x), dim=1)
x_stacked

tensor([[ 5.,  5.,  5.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 9.,  9.,  9.],
        [10., 10., 10.]])

In [60]:
x_hstack = torch.hstack((x, x, x))
x_hstack

tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10.])

In [61]:
x_vstack = torch.vstack((x, x, x))
x_vstack

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [62]:
x_reshaped

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [63]:
x_reshaped.shape

torch.Size([1, 10])

In [64]:
# tensor.squeeze() remove all single dimension from a target tensor
print(f"Previous tensor\t: {x_reshaped}")
print(f"Previous shape\t: {x_reshaped.shape}")

# Remove extra dimension froms from x_reshaped
x_squeeze = x_reshaped.squeeze()
print(f"\nNew tensor\t: {x_squeeze}")
print(f"New shape\t: {x_squeeze.shape}")

Previous tensor	: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape	: torch.Size([1, 10])

New tensor	: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape	: torch.Size([10])


In [65]:
# tensor.unsqueeze() - adds a single dimension from a target tensor at a specific dim
print(f"Previous tensor\t: {x_reshaped}")
print(f"Previous shape\t: {x_reshaped.shape}")

# Add an extra dimension with unsqueeze
x_unsqueeze = x_reshaped.unsqueeze(dim=0) # axis = 0
print(f"New tensor\t: {x_unsqueeze}")
print(f"New shape\t: {x_unsqueeze.shape}")

Previous tensor	: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape	: torch.Size([1, 10])
New tensor	: tensor([[[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]])
New shape	: torch.Size([1, 1, 10])


In [66]:
# tensor.permute() - rearranges the dimensions of the viewed tensor in a specific order (share the memory of the target tensor)
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2 , 0 , 1) # shift axis 0 -> 1, axis 1 -> 2, 2 -> 0
print(f"Previous shape\t: {x_original.shape}")
print(f"New shape\t: {x_permuted.shape}") # [colour_channels, height, width]


Previous shape	: torch.Size([224, 224, 3])
New shape	: torch.Size([3, 224, 224])


In [67]:
x_permuted[0,0,0] = 5
x_original[0,0,0], x_permuted[0,0,0] # they share the same memory

(tensor(5.), tensor(5.))

## **5. Indexing (Select Data from Tensors)**

In [68]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.size()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
# Indexing on the ax 0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
# Indexing on the middle bracket
x[0, 0]

tensor([1, 2, 3])

In [71]:
# Indexing on the most inner bracket (last dimension)
x[0, 0, 0]

tensor(1)

In [72]:
# We can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [73]:
# Get all values of the 0th and 1st dimension but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [74]:
# Get the last value of 1st and 2nd dimension
x[:, -1, -1]

tensor([9])

## **6. PyTorch Tensors and NumPy**

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [75]:
# NumPy array to tensor
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
array.dtype, torch.arange(1., 8.).dtype # default data of NumPy and PyTorch

(dtype('float64'), torch.float32)

In [77]:
# Change the value of array, and see what it will do to `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [78]:
# It will change the tensor too cause `+=` is an `in place` operation
array += 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
# Change the tensor, and what happen to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [81]:
tensor += 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## **7. Reproducibility (Trying to Take Random Out of Random)**

To reduce the randomness in creating a random array or tensor comes the concept of `random seed`

In [82]:
# Create 2 random tensor
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A)
print(tensor_B)
print(tensor_A == tensor_B)

tensor([[0.8044, 0.7560, 0.5332, 0.9322],
        [0.1437, 0.2574, 0.3745, 0.7689],
        [0.6999, 0.9207, 0.1303, 0.5670]])
tensor([[0.4679, 0.6106, 0.3163, 0.8866],
        [0.9829, 0.7846, 0.7733, 0.3747],
        [0.1212, 0.8837, 0.3195, 0.7704]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [83]:
# Let's make some random but reproducable tensor using `torch.manual_seed()`
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3, 4)

print(tensor_C)
print(tensor_D)
print(tensor_C == tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## **8. Running Tensors and PyTorch Objects on GPUs**

GPUs = faster computation on numbers, [CUDA](https://docs.pytorch.org/docs/stable/cuda.html) + NVIDIA hardware + PyTorch working behind the scene to make everything happens

### 8.1 Getting a GPUs
* Easiest - use google colab for free GPU (option to upgrade as well)
* Use our own GPU - see this post to see what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
* Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and acces them

For point 2 and 3 pyTorch and GPU drivers (CUDA) takes a little bit setting up to do this refers to PyTorch set up documentation: https://pytorch.org/get-started/locally/

In [84]:
!nvidia-smi

Sun Mar  8 19:20:21 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 8.2 Check for GPU acces with PyTorch

In [85]:
# Check for GPU acces with PyTorch
torch.cuda.is_available()

True

### 8.3 [Device agnostic code](https://pytorch.org/docs/stable/notes/cuda.html)
e.g. run with GPU if available, else default to CPU

In [86]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [87]:
# Count number of devices
torch.cuda.device_count()

2

### 8.4 Putting tensors (and models) on the GPU

The reason for using GPU is for faster computation

In [88]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on the GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [89]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 8.5 Moving tensors back to the CPU

In [90]:
# If tensor is on the GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [91]:
# To fix GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])